---
- name: Install and configure dnsmasq
  hosts: all
  become: yes
  tasks:
    - name: Install dnsmasq
      package:
        name: dnsmasq
        state: present

    - name: Create dnsmasq config file
      template:
        src: templates/dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
      notify:
        - restart dnsmasq

    - name: Restart dnsmasq service
      service:
        name: dnsmasq
        state: restarted
      handlers:
        - name: restart dnsmasq
          service:
            name: dnsmasq
            state: restarted
